on: [push, pull_request]

name: ci

jobs:

  build-test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.50.0 # STABLE
          - 1.45.0 # MSRV
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Generate cache key
        run: echo "${{ matrix.rust }}"
      - name: Set default toolchain
        run: rustup default ${{ matrix.rust }}
      - name: Set profile
        run: rustup set profile minimal
      - name: Add clippy
        run: rustup component add clippy
      - name: Update toolchain
        run: rustup update
      - name: Build
        run: cargo build
      - name: Clippy
        run: cargo clippy
